Vagrant.configure("2") do |config|
  config.vm.define "samba" do |smb|
    smb.vm.box = "ubuntu/xenial64"
    smb.vm.network "public_network", ip: "10.71.13.20"

    smb.vm.provider "virtualbox" do |smb|
      smb.memory = "1024"
      smb.name = "Samba-LB01"
    end

    smb.vm.hostname = "Samba-LB01"
  end                                                                                               
                                                                                                    #config.vm.network "forwarded_port", guest: 80, host: 8080 #, host_ip: "127.0.0.1"
                                                                                                    #config.vm.network "forwarded_port", guest: 445, host: 445, protocol:"tcp"
                                                                                                    #config.vm.network "forwarded_port", guest: 137, host: 137, protocol:"udp"
                                                                                                    #config.vm.network "forwarded_port", guest: 138, host: 138, protocol:"udp"
                                                                                                    #config.vm.network "forwarded_port", guest: 139, host: 139, protocol:"tcp"

   config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get install ufw
    sudo ufw enable -y
    sudo ufw allow 80/tcp
    sudo ufw allow 445/tcp

     apt-get install -y apache2
     echo "
<html>
  <head>
      <title>Vagrant</title>
  </head>
  <body>
      <h1>Vagrant Autoinstallation</h1>
      <br>
      <p>Diese VM/Webseite wurde mit Vagrant automatisch erstellt.</p>
  </body>

</html>
     " > /var/www/html/index.html
    
     sudo useradd samba --shell /bin/false                                     #Add User "samba"
     echo Test | passwd samba --stdin
     
     sudo useradd samba2 --shell /bin/false                                    #Add User "samba2"
     echo samba2 | passwd Test2 --stdin

     sudo apt-get install -y samba
     #sudo smbpasswd -a samba                                                   #Define samba-Password for User
     (echo Test; echo Test) | smbpasswd -s -a samba
     (echo Test2; echo Test2) | smbpasswd -s -a samba2

    sudo mkdir /var/FileShare

     sudo echo "
     
# HTML-Share
[SambaShare]
  comment = Foldershare for Apache
  path = /var/www/html
  read only = no
  guest ok = no
  writeable = yes
  valid users = samba

     
     " >> /etc/samba/smb.conf

     sudo echo "
     
# File-Share
[File]
  comment = Foldershare for Files
  path = /var/FileShare
  read only = no
  guest ok = no
  writeable = yes
  valid users = samba2

          
          " >> /etc/samba/smb.conf

     sudo /etc/init.d/smbd restart

     sudo chmod 777 /var/www/html

     sudo service smbd restart
     
     
     sudo ufw enable -y

   SHELL
end