Vagrant.configure("2") do |config|
  config.vm.define "samba" do |smb|
    smb.vm.box = "ubuntu/xenial64"
    smb.vm.network "public_network", ip: "10.71.13.20"

    smb.vm.provider "virtualbox" do |smb|
      smb.memory = "1024"
      smb.name = "Samba-LB01"
    end

    smb.vm.hostname = "Samba-LB01"
  end 

   config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get install ufw
    sudo ufw --force enable
    sudo ufw default deny incoming
    sudo ufw allow 22/tcp
    sudo ufw allow 80/tcp
    sudo ufw allow 445/tcp

     apt-get install -y apache2
     echo "
<html>
  <head>
      <title>Vagrant</title>
  </head>
  <body>
      <h1>Vagrant Autoinstallation</h1>
      <br>
      <p>Diese VM/Webseite wurde mit Vagrant automatisch erstellt.</p>
  </body>

</html>
     " > /var/www/html/index.html

     sudo useradd samba --shell /bin/false                                     #Add User "samba"
     echo Test | passwd samba --stdin                                          # Set Password of user "samba"

     sudo useradd samba2 --shell /bin/false                                    #Add User "samba2"
     echo Test2 | passwd samba2 --stdin                                        # Set Password of user "samba2"

     sudo apt-get install -y samba
     (echo Test; echo Test) | smbpasswd -s -a samba                            #Define samba-Password for User "samba"
     (echo Test2; echo Test2) | smbpasswd -s -a samba2                         #Define samba-Password for User "samba2"

    sudo mkdir /var/FileShare

     sudo echo "
     
# HTML-Share
[HTMLShare]
  comment = Foldershare for Apache
  path = /var/www/html
  read only = no
  guest ok = no
  writeable = yes
  valid users = samba

     
     " >> /etc/samba/smb.conf

     sudo echo "
     
# File-Share
[FileShare]
  comment = Foldershare for Files
  path = /var/FileShare
  read only = no
  guest ok = no
  writeable = yes
  valid users = samba2

          
          " >> /etc/samba/smb.conf

     sudo /etc/init.d/smbd restart

     sudo chmod 777 /var/www/html
     sudo chmod 777 /var/FileShare

     sudo service smbd restart

   SHELL
end